version: '3'
services:
  dashboard:
    build: .
    command: [ "npm", "run", "dev" ]
    volumes:
      - type: bind
        source: .
        target: /swap-dashboard
      - type: volume
        source: node_modules
        target: /swap-dashboard/node_modules
      - node_modules:/swap-dashboard/node_modules
    ports:
      - "3001:3001"
    tty: true
    stdin_open: true

volumes:
  node_modules:
