version: '3'
services:
  dashboard:
    build: .
    command: [ "npm", "run", "dev" ]
    volumes:
      - type: bind
        source: .
        target: /swap-dashboard
    ports:
      - "3001:3001"
    tty: true
    stdin_open: true

networks:
  default:
    name: swap-web_default
    external: true
